### ISSUE TITLE
gravity calibration error at point 15

### ISSUE THREAD

**Issue by AYBarrett** [BarrettTechnology/proficio_toolbox#3]
gravity calibration shows the following error at point 15:

stack trace:
  /usr/local/lib/libbarrett.so.1.2 : barrett::detail::myTerminate()+0x13
  /usr/lib/x86_64-linux-gnu/libstdc++.so.6 : ()+0xb5846
  /usr/lib/x86_64-linux-gnu/libstdc++.so.6 : ()+0xb5873
  /usr/lib/x86_64-linux-gnu/libstdc++.so.6 : ()+0xb596e
  /usr/local/lib/libconfig++.so.9 : libconfig::Config::handleError() const+0x4f
  /usr/local/lib/libconfig++.so.9 : libconfig::Config::writeFile(char const*)+0x20
  bt-wam-gravitycal : int wam_main<3ul>(int, char**, barrett::ProductManager&, barrett::systems::Wam<3ul>&)+0x24a7
  bt-wam-gravitycal : main()+0x69
  /lib/x86_64-linux-gnu/libc.so.6 : __libc_start_main()+0xed
  bt-wam-gravitycal() [0x438d8d]
terminate called after throwing an instance of 'libconfig::FileIOException'
  what():  FileIOException
Aborted (core dumped)

**Comment by mhariharasudan** [comment]
This is due to the lack of write permission to ~/.barrett directory. This is fixed in commit #8cd22bcc0f3b730e40fa1757db0185e0c508c41a
